DROP TABLE IF EXISTS VIDEO;

CREATE TABLE VIDEO (
       FILE_ID               INT NOT NULL AUTO_INCREMENT,
       FILE_STORE_PATH       VARCHAR(2000) NOT NULL,
       FILE_EXTSN            VARCHAR(20) NOT NULL,
       ORIGIN_FILE_NM        VARCHAR(255) NOT NULL,
       STORE_FILE_NM         VARCHAR(255) NOT NULL,
       PRIMARY KEY (FILE_ID)
);